name: lint-test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
permissions:
  contents: read

defaults:
  run:
    shell: bash
jobs:
  lint:
    name: Lint files
    runs-on: ubuntu-latest
    steps:
      -  uses: actions/setup-go@v2
        with:
          go-version: 1.17.1
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: golangci/golangci-lint-action@v3
        with:
          version: latest
  test:
    name: Run tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17.1
      - uses: actions/checkout@v3
      - run: go test -cover -race -vet=off ./...
