name: Lint
on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    name: Lint files
    runs-on: ubuntu-latest
    steps:
      - name: Check out sveltin
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17.1
          cache: true
          cache-dependency-path: go.sum

      - name: Install Go modules
        run: go mod download

      - name: Verify dependencies
        run: go mod verify

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
