name: lint-test
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read
jobs:
  golangci:
    runs-on: ubuntu-latest
    steps:
      - name: Setup go 1.17.1
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.1
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          # Optional: show only new issues if it's a pull request. The default value is `false`.
          # only-new-issues: true

          # Optional: if set to true then the all caching functionality will be complete disabled,
          #           takes precedence over all other caching options.
          skip-cache: false

          # Optional: if set to true then the action don't cache or restore ~/go/pkg.
          skip-pkg-cache: false

          # Optional: if set to true then the action don't cache or restore ~/.cache/go-build.
          skip-build-cache: false
      - name: Run tests
        run: go test -race -vet=off ./...
